# Generated by Django 2.2.6 on 2021-08-05 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210804_2117'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check_following',
        ),
    ]
